version: '3.6'
services:
  app:
    image: nginx:latest
    container_name: maze
    restart: unless-stopped
    volumes:
      - ./:/var/www/maze/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

# http://maze.com/html/welcome.html






